---
- name: Setup all servers
  hosts: all
  vars_files:
    - vault.yml
  vars:
    ansible_become_pass: '{{ ansible_become_pass }}'
  become: yes
  tasks:
    - name: Copy SSH certificate to authorized_keys
      authorized_key:
        user: jarred
        key: "{{ lookup('file', '/home/jarred/.ssh/id_rsa.pub') }}"
        state: present
      become: yes
    - name: Install tree
      apt:
        name: tree
        state: present
      become: yes
