---
- name: Setup all servers
  hosts: all
  vars_files:
    - vault.yml
  vars:
    ansible_become_pass: '{{ ansible_become_pass }}'
  become: yes
  tasks:
    - name: Copy SSH certificate to authorized_keys
      authorized_key:
        user: jarred
        key: "{{ lookup('file', '/home/jarred/.ssh/id_rsa.pub') }}"
        state: present
      become: yes
    - name: Install tree
      apt:
        name: tree
        state: present
      become: yes
    - name: apt upgrade and update
      apt: 
        upgrade: yes
        update_cache: yes
        
    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: reboot_required_file

    - name: Reboot the server (if required).
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes
      
