---
media:
  hosts:
    docker-01:
      ansible_host: 192.168.1.191
    docker-02:
      ansible_host: 192.168.1.29
management:
  hosts:
    ansible-01:
      ansible_host: localhost
      ansible_connection: local